# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-19 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MC', 'Multiple Choice'), ('SC', 'Single Choice'), ('TX', 'Text')], default=None, max_length=23)),
                ('widget', models.CharField(choices=[('TEXT', 'Text'), ('SELECT_LIST', 'Select_list'), ('CHECK_BOX', 'Check_box'), ('RADIO_BUTTON', 'Radio_button')], default=None, max_length=23)),
                ('question_text', models.CharField(max_length=22)),
            ],
            options={
                'ordering': ['question_text', 'survey'],
            },
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_title', models.CharField(default=None, max_length=22, unique=True, verbose_name='survey Title')),
            ],
            options={
                'ordering': ['survey_title'],
            },
        ),
        migrations.AddField(
            model_name='field',
            name='survey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form_builder.survey'),
        ),
    ]
