# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-15 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionaire_title', models.CharField(default=None, max_length=22, verbose_name='Questionaire')),
                ('Author', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form_builder.survey'),
        ),
    ]
