# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-15 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(default=None, max_length=22)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_builder.field')),
            ],
        ),
    ]
