# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-19 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='widget',
            field=models.CharField(choices=[('TEXT', 'Text'), ('SELECT_LIST', 'Select_list'), ('CHECK_BOX', 'Select_box'), ('RADIO_BUTTON', 'Radio_button')], default=None, max_length=23),
        ),
    ]
