# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-19 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0002_field_widget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='option',
        ),
        migrations.AlterField(
            model_name='field',
            name='widget',
            field=models.CharField(choices=[('TEXT', 'Text'), ('SELECT_LIST', 'Select_list'), ('CHECK_BOX', 'Check_box'), ('RADIO_BUTTON', 'Radio_button')], default=None, max_length=23),
        ),
    ]
