# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-15 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form_builder.survey'),
        ),
    ]
