# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-15 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0003_feedback_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_builder.field'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='questionaire_title',
            field=models.CharField(default=None, max_length=22, unique=True, verbose_name='Questionaire'),
        ),
    ]
