# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-15 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_auto_20191115_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='project',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question',
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
