# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-15 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0005_auto_20191115_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='project',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='questionaire_title',
            new_name='survey_title',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Author',
        ),
    ]
